# Generated by Django 5.0 on 2023-12-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula1_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('season_start', models.DateField()),
                ('season_end', models.DateField()),
                ('races', models.ManyToManyField(to='formula1_app.race')),
                ('teams', models.ManyToManyField(to='formula1_app.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
