# Generated by Django 5.0 on 2023-12-30 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula1_app', '0002_championship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championship',
            name='races',
        ),
        migrations.RemoveField(
            model_name='championship',
            name='teams',
        ),
        migrations.AddField(
            model_name='championship',
            name='races',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formula1_app.race'),
        ),
        migrations.AddField(
            model_name='championship',
            name='teams',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formula1_app.team'),
        ),
    ]
