# Generated by Django 5.0 on 2023-12-30 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula1_app', '0003_remove_championship_races_remove_championship_teams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championship',
            name='races',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula1_app.race'),
        ),
        migrations.AlterField(
            model_name='championship',
            name='teams',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula1_app.team'),
        ),
    ]
