# Generated by Django 5.0 on 2023-12-30 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula1_app', '0004_alter_championship_races_alter_championship_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formula1_app.driver'),
            preserve_default=False,
        ),
    ]
