# Generated by Django 5.0 on 2023-12-31 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula1_app', '0010_remove_championship_image_remove_result_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='championship',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formula1_app.team'),
            preserve_default=False,
        ),
    ]
